/*
 * Gaussian extractor
 * probabilistic description of a map
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.fabrizio.gps.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
