/*
 * Gaussian extractor
 * probabilistic description of a map
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.fabrizio.gps.api;

import com.example.fabrizio.gps.ApiCallback;
import com.example.fabrizio.gps.ApiClient;
import com.example.fabrizio.gps.ApiException;
import com.example.fabrizio.gps.ApiResponse;
import com.example.fabrizio.gps.Configuration;
import com.example.fabrizio.gps.Pair;
import com.example.fabrizio.gps.ProgressRequestBody;
import com.example.fabrizio.gps.ProgressResponseBody;
import com.google.gson.reflect.TypeToken;

import java.io.IOException;
import java.lang.reflect.Type;
import java.net.SocketTimeoutException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CalculatorApi {
    private ApiClient apiClient;

    public CalculatorApi() {
        this(Configuration.getDefaultApiClient());
    }

    public CalculatorApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return apiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    /**
     * Build call for compute
     * @param latitude  (required)
     * @param longitude  (required)
     * @param progressListener Progress listener
     * @param progressRequestListener Progress request listener
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     */
    public com.squareup.okhttp.Call computeCall(String latitude, String longitude,String altitude, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/calculator/{latitude}/{longitude}/{altitude}"
            .replaceAll("\\{" + "latitude" + "\\}", apiClient.escapeString(latitude))
            .replaceAll("\\{" + "longitude" + "\\}", apiClient.escapeString(longitude))
                .replaceAll("\\{" + "altitude" + "\\}", apiClient.escapeString(altitude));

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();

        Map<String, String> localVarHeaderParams = new HashMap<String, String>();

        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "text/plain"
        };
        final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) localVarHeaderParams.put("Accept", localVarAccept);

        final String[] localVarContentTypes = {
            
        };
        final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);
        localVarHeaderParams.put("Content-Type", localVarContentType);

        if(progressListener != null) {
            apiClient.getHttpClient().networkInterceptors().add(new com.squareup.okhttp.Interceptor() {
                @Override
                public com.squareup.okhttp.Response intercept(com.squareup.okhttp.Interceptor.Chain chain) throws IOException {
                    com.squareup.okhttp.Response originalResponse = chain.proceed(chain.request());
                    return originalResponse.newBuilder()
                    .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                    .build();
                }
            });
        }

        String[] localVarAuthNames = new String[] {  };
        return apiClient.buildCall(localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarFormParams, localVarAuthNames, progressRequestListener);
    }

    @SuppressWarnings("rawtypes")
    private com.squareup.okhttp.Call computeValidateBeforeCall(String latitude, String longitude,String altitude, final ProgressResponseBody.ProgressListener progressListener, final ProgressRequestBody.ProgressRequestListener progressRequestListener) throws ApiException {
        
        // verify the required parameter 'latitude' is set
        if (latitude == null) {
            throw new ApiException("Missing the required parameter 'latitude' when calling compute(Async)");
        }
        
        // verify the required parameter 'longitude' is set
        if (longitude == null) {
            throw new ApiException("Missing the required parameter 'longitude' when calling compute(Async)");
        }
        if (altitude == null) {
            throw new ApiException("Missing the required parameter 'latitude' when calling compute(Async)");
        }

        com.squareup.okhttp.Call call = computeCall(latitude, longitude, altitude, progressListener, progressRequestListener);
        return call;

    }

    /**
     * calcolatrice semplice
     * calcola i parametri delle gaussiane che descrivono la mappa
     * @param latitude  (required)
     * @param longitude  (required)
     * @return String
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public String compute(String latitude, String longitude,String altitude) throws ApiException {
        try {
            ApiResponse<String> resp;
            if (computeWithHttpInfo(latitude, longitude, altitude) != null ){
                resp = computeWithHttpInfo(latitude, longitude, altitude);
                return resp.getData();
            }
        }
        catch(ApiException e){
            throw new ApiException(e);
        }
        return null;
    }

    /**
     * calcolatrice semplice
     * calcola i parametri delle gaussiane che descrivono la mappa
     * @param latitude  (required)
     * @param longitude  (required)
     * @return ApiResponse&lt;String&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     */
    public ApiResponse<String> computeWithHttpInfo(String latitude, String longitude,String altitude) throws ApiException {
        com.squareup.okhttp.Call call = computeValidateBeforeCall(latitude, longitude,altitude, null, null);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        return apiClient.execute(call, localVarReturnType);
    }

    /**
     * calcolatrice semplice (asynchronously)
     * calcola i parametri delle gaussiane che descrivono la mappa
     * @param latitude  (required)
     * @param longitude  (required)
     * @param callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     */
    public com.squareup.okhttp.Call computeAsync(String latitude, String longitude,String altitude, final ApiCallback<String> callback) throws ApiException {

        ProgressResponseBody.ProgressListener progressListener = null;
        ProgressRequestBody.ProgressRequestListener progressRequestListener = null;

        if (callback != null) {
            progressListener = new ProgressResponseBody.ProgressListener() {
                @Override
                public void update(long bytesRead, long contentLength, boolean done) {
                    callback.onDownloadProgress(bytesRead, contentLength, done);
                }
            };

            progressRequestListener = new ProgressRequestBody.ProgressRequestListener() {
                @Override
                public void onRequestProgress(long bytesWritten, long contentLength, boolean done) {
                    callback.onUploadProgress(bytesWritten, contentLength, done);
                }
            };
        }

        com.squareup.okhttp.Call call = computeValidateBeforeCall(latitude, longitude,altitude, progressListener, progressRequestListener);
        Type localVarReturnType = new TypeToken<String>(){}.getType();
        apiClient.executeAsync(call, localVarReturnType, callback);
        return call;
    }
}
